import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

import { SCENE_TUNING } from '../src/scene-tuning.js';
import { isGuideLevelActive } from '../src/scene-view.js';

test('guide hand targets Level12 vehicle 34 only with the first-step mask disabled', async () => {
  const tuning = SCENE_TUNING.vehicleGuideHand;
  const firstClickGuide = SCENE_TUNING.firstClickGuide;
  const mainSource = await readFile(new URL('../src/main.js', import.meta.url), 'utf8');
  const editorSource = await readFile(new URL('../src/scene-editor.js', import.meta.url), 'utf8');
  const stylesSource = await readFile(new URL('../src/styles.css', import.meta.url), 'utf8');
  const viewSource = await readFile(new URL('../src/scene-view.js', import.meta.url), 'utf8');
  const emoji = SCENE_TUNING.passengerEmoji;
  const hint = SCENE_TUNING.guideHandHint;
  const retry = SCENE_TUNING.retryButton;

  assert.equal(tuning.levelKey, 'level12');
  assert.equal(tuning.vehicleId, 34);
  assert.equal(tuning.size, 2.12);
  assert.equal(tuning.offsetX, 0.25);
  assert.equal(tuning.approachOffsetX, 0.62);
  assert.ok(tuning.farScale > tuning.nearScale, 'hand should shrink while moving from right to left');
  assert.equal(firstClickGuide.enabled, 0);
  assert.equal(firstClickGuide.levelKey, 'level12');
  assert.equal(firstClickGuide.vehicleId, 34);
  assert.equal(firstClickGuide.durationSeconds, 3);
  assert.equal(firstClickGuide.maskOpacity, 0.8);
  assert.equal(firstClickGuide.holePadding, 15);
  assert.equal(firstClickGuide.holeScaleX, 0.62);
  assert.equal(firstClickGuide.holeScaleY, 0.62);
  assert.equal(emoji.autoHideOnVehicleEnabled, 0);
  assert.equal(emoji.autoHideOnVehicleLevelKey, 'level29');
  assert.equal(emoji.autoHideOnVehicleId, 1);
  assert.equal(emoji.animationDelaySeconds, 0);
  assert.equal(hint.enabled, 0);
  assert.equal(hint.x, 540);
  assert.equal(hint.y, 1580);
  assert.equal(retry.enabled, 1);
  assert.equal(retry.x, 960);
  assert.equal(retry.y, 180);
  assert.equal(retry.size, 76);
  assert.equal(isGuideLevelActive(tuning, 'level12'), true);
  assert.equal(isGuideLevelActive(tuning, 'level10'), false);
  assert.equal(isGuideLevelActive(firstClickGuide, 'level12'), true);
  assert.equal(isGuideLevelActive(firstClickGuide, 'level10'), false);
  assert.match(viewSource, /texture\.wrapS = THREE\.RepeatWrapping/);
  assert.match(viewSource, /texture\.repeat\.x = -1/);
  assert.match(viewSource, /texture\.offset\.x = 1/);
  assert.match(viewSource, /createFirstClickGuideMask/);
  assert.match(viewSource, /updateFirstClickGuideMask/);
  assert.match(viewSource, /updateFirstClickGuideHand/);
  assert.match(viewSource, /first-click-guide-mask/);
  assert.match(viewSource, /first-click-guide-hand/);
  assert.match(viewSource, /durationSeconds/);
  assert.match(viewSource, /holeScaleX/);
  assert.match(viewSource, /holeScaleY/);
  assert.match(viewSource, /SCENE_TUNING\.firstClickGuide\?\.enabled/);
  assert.match(viewSource, /levelKey === activeLevelKey/);
  assert.match(viewSource, /!isGuideLevelActive\(tuning\)/);
  assert.match(viewSource, /!guide\.enabled \|\| !isGuideLevelActive\(guide\)/);
  assert.match(mainSource, /guideHandHintShown/);
  assert.match(mainSource, /showGuideHandHintAfterVehicleClick/);
  assert.match(mainSource, /GUIDE_HAND_HINT_LONG_PRESS_MS = 2000/);
  assert.match(mainSource, /dismissGuideHandHint\(\)/);
  assert.match(mainSource, /guideHandHint\.enabled/);
  assert.match(mainSource, /projectCenteredDesignPoint/);
  assert.match(mainSource, /result\?\.ok\) \{[\s\S]*showGuideHandHintAfterVehicleClick/);
  assert.doesNotMatch(mainSource, /guide-locked/);
  assert.doesNotMatch(mainSource, /getActiveFirstClickGuideTargetId/);
  assert.match(mainSource, /migrateGuideHandMotionTuning/);
  assert.match(mainSource, /Number\(guideHand\.vehicleId\) === 1/);
  assert.match(mainSource, /Number\(guideHand\.offsetX\) === -0\.38/);
  assert.match(mainSource, /Number\(guideHand\.approachOffsetX\) === -0\.62/);
  assert.match(mainSource, /PASSENGER_EMOJI_HIDE_STATES/);
  assert.match(mainSource, /updatePassengerEmojiAutoHide/);
  assert.match(mainSource, /passengerEmojiAnimationStartedAt/);
  assert.match(mainSource, /animationDelaySeconds/);
  assert.match(mainSource, /startPassengerEmojiAnimation/);
  assert.match(mainSource, /autoHideOnVehicleLevelKey/);
  assert.match(mainSource, /autoHideOnVehicleId/);
  assert.match(mainSource, /guide\.levelKey = 'level12'/);
  assert.match(mainSource, /guide\.vehicleId = 34/);
  assert.match(stylesSource, /\.first-click-guide-hand/);
  assert.match(stylesSource, /scaleX\(-1\)/);
  assert.match(editorSource, /firstClickGuide\.enabled/);
  assert.match(editorSource, /vehicleGuideHand\.levelKey/);
  assert.match(editorSource, /firstClickGuide\.levelKey/);
  assert.match(editorSource, /firstClickGuide\.vehicleId/);
  assert.match(editorSource, /firstClickGuide\.durationSeconds/);
  assert.match(editorSource, /firstClickGuide\.maskOpacity/);
  assert.match(editorSource, /firstClickGuide\.holeScaleX/);
  assert.match(editorSource, /firstClickGuide\.holeScaleY/);
  assert.match(editorSource, /passengerEmoji\.autoHideOnVehicleEnabled/);
  assert.match(editorSource, /passengerEmoji\.autoHideOnVehicleLevelKey/);
  assert.match(editorSource, /passengerEmoji\.autoHideOnVehicleId/);
  assert.match(editorSource, /passengerEmoji\.animationDelaySeconds/);
  assert.match(editorSource, /guideHandHint\.enabled/);
  assert.match(editorSource, /guideHandHint\.x/);
  assert.match(editorSource, /guideHandHint\.y/);
  assert.match(editorSource, /retryButton\.enabled/);
  assert.match(editorSource, /retryButton\.x/);
  assert.match(editorSource, /retryButton\.y/);
  assert.match(editorSource, /retryButton\.size/);
  assert.match(mainSource, /retryCurrentLevel/);
  assert.match(mainSource, /retryWithTransition/);
  assert.match(mainSource, /retryTransition/);
  assert.match(mainSource, /guideHandHintDismissed = false/);
  assert.match(mainSource, /game\.reset\(\)/);
  assert.match(mainSource, /levelSession\.reset\(\)/);
  assert.match(mainSource, /game\.reset\(\)/);
  assert.match(stylesSource, /\.retry-button/);
  assert.match(stylesSource, /border-radius: 50%/);
  assert.match(stylesSource, /\.retry-transition/);
  assert.match(stylesSource, /background: #000/);
  assert.match(stylesSource, /\.guide-hand-hint/);
  assert.match(stylesSource, /pointer-events: none/);
  assert.match(viewSource + mainSource, /main-guide-hand_q80\.webp/);
  assert.match(viewSource + mainSource, /HOLD TO SPEED UP/);
});
